version: "3.8"

services:
  
  db:
    image: mysql:5.7
    container_name: ssafy_db
    restart: always

    ports:
      - "32000:3306"
    
    environment:
      MYSQL_ROOT_PASSWORD: ssafy
      TZ: "Asia/Seoul"
    privileged: true

    volumes:
      - ./db:/docker-entrypoint-initdb.d
    networks:
      - backend

  openvidu:
    //

  app:
    build:
      context: ./
    container_name: ssafy_app
    restart: always
    ports:
      - "8080:8080"
      - "8443:8443"
    environment:
      TZ: "Asia/Seoul"
    SPRING_DATASOURCE_URL:
      "jdbc:mysql://db:3306/ssafy_web?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Seoul&zeroDateTimeBehavior=convertToNull&rewriteBatchedStatements=true"
    
    JAVA_TOOL_OPTIONS: ""
    server.address: 0.0.0.0
  
  depends_on:
    - db
    - openvidu
  networks:
    - backend

networks:
backend: